# Generated by Django 4.0.4 on 2022-08-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_checkout_checkoutproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='mode',
            field=models.CharField(default='COD', max_length=20),
        ),
    ]
