# Generated by Django 4.0.4 on 2022-08-05 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_checkout_mode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='orderststus',
            new_name='orderstatus',
        ),
    ]
