# Generated by Django 4.0.4 on 2022-08-05 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_rename_orderststus_checkout_orderstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='paymentststus',
            new_name='paymentstatus',
        ),
    ]
