# Generated by Django 4.0.4 on 2022-08-09 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_newslatter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslatter',
            name='email',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
